apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.stableName }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
    role: stable
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "podinfo.selectorLabels" . | nindent 4 }}
