apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-two
  namespace: gitops-prod
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: prod
            namespace: podinfo-two-prod
  template:
    metadata:
      name: 'podinfo-two-{{ .env }}'
      labels:
        harness.io/serviceRef: apptwo
        harness.io/envRef: '{{ .env }}'
        app: podinfo
        environment: '{{ .env }}'
    spec:
      project: appteamtwo
      sources:
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          path: chart
          helm:
            releaseName: 'podinfo-two-{{ .env }}'
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/envs/{{ .env }}.yaml'
            values: |
              securityContext:
                runAsUser: null
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      ignoreDifferences:
        - group: ""
          kind: Service
          jsonPointers:
            - /spec/selector
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
