#!/usr/bin/env bash
# Install the Karmada control plane on the CRC/OpenShift hub cluster.
# Idempotent-ish: safe to re-run to restart the port-forward after a reboot.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/.run"
HUB_CONTEXT="${HUB_CONTEXT:-crc-admin}"
KARMADA_NS="karmada-system"
STORAGE_CLASS="crc-csi-hostpath-provisioner"
LOCAL_API_PORT="${LOCAL_API_PORT:-32443}"   # local port-forward port on the Mac
KCFG="$RUN_DIR/karmada-apiserver.config"

mkdir -p "$RUN_DIR"

start_port_forward() {
  pkill -f "port-forward.*karmada-apiserver" 2>/dev/null || true
  nohup kubectl --context "$HUB_CONTEXT" -n "$KARMADA_NS" \
    port-forward svc/karmada-apiserver "${LOCAL_API_PORT}:5443" \
    >"$RUN_DIR/port-forward.log" 2>&1 &
  sleep 3
}

# Re-run mode: control plane already installed -> just restore the port-forward
if [[ -f "$KCFG" ]] && kubectl --context "$HUB_CONTEXT" -n "$KARMADA_NS" get deploy karmada-apiserver >/dev/null 2>&1; then
  echo "== Karmada already installed; (re)starting port-forward only"
  start_port_forward
  kubectl --kubeconfig "$KCFG" get clusters
  exit 0
fi

echo "== 1/4 SCC: let karmada-system pods run with their image UIDs (demo-grade)"
oc --context "$HUB_CONTEXT" adm policy add-scc-to-group anyuid \
  "system:serviceaccounts:${KARMADA_NS}"

echo "== 2/4 karmadactl init (etcd on PVC, extra SAN for port-forward access)"
karmadactl init \
  --kubeconfig "${KUBECONFIG:-$HOME/.kube/config}" \
  --context "$HUB_CONTEXT" \
  --namespace "$KARMADA_NS" \
  --etcd-storage-mode PVC \
  --storage-classes-name "$STORAGE_CLASS" \
  --cert-external-ip=127.0.0.1 \
  --karmada-data "$RUN_DIR" \
  --karmada-pki "$RUN_DIR/pki"

[[ -f "$KCFG" ]] || { echo "ERROR: $KCFG was not generated by karmadactl init"; exit 1; }

echo "== 3/4 Point the Karmada kubeconfig at the local port-forward (CRC exposes no NodePorts to the Mac)"
CLUSTER_NAME=$(kubectl --kubeconfig "$KCFG" config view -o jsonpath='{.clusters[0].name}')
kubectl --kubeconfig "$KCFG" config set-cluster "$CLUSTER_NAME" \
  --server="https://127.0.0.1:${LOCAL_API_PORT}"

echo "== 4/4 Start port-forward (background, log: .run/port-forward.log)"
start_port_forward

echo "== Smoke test"
kubectl --kubeconfig "$KCFG" api-resources --api-group=policy.karmada.io
kubectl --kubeconfig "$KCFG" get clusters || true

cat <<EOF

Karmada control plane installed.
  Karmada API kubeconfig : $KCFG
  Reachable at           : https://127.0.0.1:${LOCAL_API_PORT} (via port-forward)

Next: ./scripts/02-join-members.sh
EOF
