apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-np
  namespace: harness-agent
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:
          - env: np
            retryLimit: 5
            retryFactor: 2

  template:
    metadata:
      name: 'podinfo-{{ .env }}'
      labels:
        harness.io/serviceRef: demoapp
        harness.io/envRef: '{{ .env }}'
        app: podinfo
        environment: '{{ .env }}'
    spec:
      project: demo-app
      sources:
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          path: chart
          helm:
            releaseName: 'podinfo-{{ .env }}'
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/envs/{{ .env }}.yaml'
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app

  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: {{ .retryLimit }}
          backoff:
            duration: 10s
            factor: {{ .retryFactor }}
            maxDuration: 3m