apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo
  namespace: gitops-agent
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - env: np
            cluster: k3d-np
          - env: live
            cluster: k3d-live
  template:
    metadata:
      name: 'podinfo-{{ .env }}'
      labels:
        app: podinfo
        environment: '{{ .env }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          path: chart
          helm:
            releaseName: 'podinfo-{{ .env }}'
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/envs/{{ .env }}.yaml'
        - repoURL: https://github.com/harness-landing-zone/pod-info-demo
          targetRevision: main
          ref: values
      destination:
        name: '{{ .cluster }}'
        namespace: podinfo
      syncPolicy:
        automated:
          prune: true
          selfHeal: false         # let the pipeline/rollout controller manage canary state
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
