workload:
  kind: Rollout
image:
  tag: v0.1
replicaCount: 3
rollout:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
analysis:
  enabled: false
monitoring:
  enabled: false
ingress:
  enabled: false
